#!/usr/bin/env bash
# Emits a deterministic Markdown report of every tool version inside the
# ubuntu-env image. Designed to run *inside* the container as a login shell so
# the toolchain PATH (/usr/local/go/bin, ~/.cargo/bin, ...) is picked up.
#
# Output is written to stdout. The format is stable (sorted, fixed columns) so
# committing the file to the repo produces a meaningful, reviewable diff.
set -euo pipefail
shopt -s lastpipe

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Run a command, return its first line (stdout+stderr merged), or empty.
_safe() {
    "$@" 2>&1 | head -n 1 || true
}

# Run a command and extract the first version-like token (e.g. "1.2.3").
_ver_token() {
    _safe "$@" | grep -oE '[0-9]+(\.[0-9]+){1,3}([._a-zA-Z0-9-]*)?' | head -n 1 || true
}

# Look up an npm-global package version directly from its package.json — more
# reliable than parsing CLI output, especially for tools that prompt or print
# banners (ng, pm2).
_npm_global_version() {
    local pkg="$1"
    local root pkg_json
    root="$(npm root -g 2>/dev/null || true)"
    pkg_json="${root}/${pkg}/package.json"
    if [ -r "$pkg_json" ]; then
        python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["version"])' "$pkg_json"
    fi
}

# Default value if the captured version is empty.
_or_na() {
    local v="${1:-}"
    [ -n "$v" ] && printf '%s' "$v" || printf 'n/a'
}

# ---------------------------------------------------------------------------
# Probe each tool
# ---------------------------------------------------------------------------

# OS
. /etc/os-release
os_label="${PRETTY_NAME:-${NAME} ${VERSION}}"

# Languages & runtimes
go_v=$(_or_na "$(go version 2>/dev/null | awk '{print $3}' | sed 's/^go//')")
java_v=$(_or_na "$(java --version 2>/dev/null | head -n 1 | awk '{print $2}')")
node_v=$(_or_na "$(node --version 2>/dev/null | sed 's/^v//')")
python_v=$(_or_na "$(python3 --version 2>/dev/null | awk '{print $2}')")
ruby_v=$(_or_na "$(ruby --version 2>/dev/null | awk '{print $2}')")
rustc_v=$(_or_na "$(rustc --version 2>/dev/null | awk '{print $2}')")

# Build tools & package managers
cargo_v=$(_or_na "$(cargo --version 2>/dev/null | awk '{print $2}')")
just_v=$(_or_na "$(just --version 2>/dev/null | awk '{print $2}')")
npm_v=$(_or_na "$(npm --version 2>/dev/null)")
pip_v=$(_or_na "$(python3 -m pip --version 2>/dev/null | awk '{print $2}')")
gem_v=$(_or_na "$(gem --version 2>/dev/null)")
bundler_v=$(_or_na "$(bundler --version 2>/dev/null | awk '{print $NF}')")

# Web frameworks & process managers
rails_v=$(_or_na "$(rails --version 2>/dev/null | awk '{print $2}')")
angular_v=$(_or_na "$(_npm_global_version @angular/cli)")
pm2_v=$(_or_na "$(_npm_global_version pm2)")

# Cloud & DevOps
aws_v=$(_or_na "$(aws --version 2>&1 | awk '{print $1}' | cut -d/ -f2)")
docker_v=$(_or_na "$(docker --version 2>/dev/null | awk '{print $3}' | sed 's/,$//')")
kubectl_v=$(_or_na "$(kubectl version --client -o json 2>/dev/null \
    | python3 -c 'import json,sys;print(json.load(sys.stdin)["clientVersion"]["gitVersion"].lstrip("v"))' 2>/dev/null)")
tofu_v=$(_or_na "$(tofu version 2>/dev/null | head -n 1 | awk '{print $2}' | sed 's/^v//')")

# AI tooling
claude_v=$(_or_na "$(claude --version 2>/dev/null | awk '{print $1}')")

# Database clients
psql_v=$(_or_na "$(psql --version 2>/dev/null | awk '{print $3}')")
mariadb_v=$(_or_na "$(mariadb --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+-MariaDB' | head -n 1)")
mongosh_v=$(_or_na "$(mongosh --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+([.-][a-zA-Z0-9]+)*' | head -n 1)")

# ---------------------------------------------------------------------------
# Emit Markdown
# ---------------------------------------------------------------------------

cat <<EOF
# Tool Versions

> Auto-generated by the ubuntu-env build pipeline. **Do not edit by hand.**
> Build timestamp, source commit and image digest are recorded in the commit
> metadata of each refresh. Versions are sampled on \`linux/amd64\` and are
> identical on \`linux/arm64\` (the image is multi-arch).

## Operating system

| Component | Version |
|---|---|
| Base image | ${os_label} |

## Languages & runtimes

| Tool | Version |
|---|---|
| Go | ${go_v} |
| Java (OpenJDK) | ${java_v} |
| Node.js | ${node_v} |
| Python | ${python_v} |
| Ruby | ${ruby_v} |
| Rust (rustc) | ${rustc_v} |

## Build tools & package managers

| Tool | Version |
|---|---|
| cargo | ${cargo_v} |
| just | ${just_v} |
| npm | ${npm_v} |
| pip | ${pip_v} |
| RubyGems | ${gem_v} |
| bundler | ${bundler_v} |

## Web frameworks & process managers

| Tool | Version |
|---|---|
| Angular CLI | ${angular_v} |
| Rails | ${rails_v} |
| PM2 | ${pm2_v} |

## Cloud & DevOps

| Tool | Version |
|---|---|
| AWS CLI | ${aws_v} |
| Docker CLI | ${docker_v} |
| kubectl | ${kubectl_v} |
| OpenTofu | ${tofu_v} |

## AI tooling

| Tool | Version |
|---|---|
| Claude Code | ${claude_v} |

## Database clients

| Tool | Version |
|---|---|
| psql (PostgreSQL) | ${psql_v} |
| mariadb / mysql | ${mariadb_v} |
| mongosh | ${mongosh_v} |
EOF
